"""Manual ticker mapping for pharma market movers companies."""

TICKER_MAP = {
    # US-listed biotech/pharma
    "Liquidia Corporation": "LQDA",
    "ASP Isotopes": "ASPI",
    "Lexicon Pharmaceuticals": "LXRX",
    "Galecto": "GLTO",
    "Allogene Therapeutics": "ALLO",
    "ImmunityBio": "IBRX",
    "Centessa Pharmaceuticals": "CNTA",
    "Sumitomo Pharma": "4506.T",
    "Celanese": "CE",
    "Sarepta Therapeutics": "SRPT",
    "Corcept Therapeutics": "CORT",
    "Summit Therapeutics": "SMMT",
    "Kodiak Sciences": "KOD",
    "Precigen": "PGEN",
    "Crescent Biopharma": "CBIO",
    "United Therapeutics": "UTHR",
    "Idorsia": "IDIA.SW",
    "Alvotech": "ALVO",
    "Apellis Pharmaceuticals": "APLS",
    "Soleno Therapeutics": "SLNO",
    "Dermapharm Holding": "DMP.DE",
    "Insmed": "INSM",
    "Natera": "NTRA",
    "Illumina": "ILMN",
    "Regencell Bioscience": "RGC",
    "Genomma Lab Internacional": "LABB.MX",
    "Inventiva": "IVA.PA",
    "Krka Group": "KRKG.LJ",
    "Prelude Therapeutics": "PRLD",
    "AC Immune": "ACIU",
    "Armata Pharmaceuticals": "ARMP",
    "AxoGen": "AXGN",
    "Mitsui Chemicals": "4183.T",
    "Mitsubishi Chemical": "4188.T",
    "Zentalis Pharmaceuticals": "ZNTL",
    "Invivyd": "IVVD",
    "Forte Biosciences": "FBRX",
    "Revolution Medicines": "RVMD",
    "TuHURA Biosciences": "HURA",
    "Spyre Therapeutics": "SYRE",
    "Twist Bioscience": "TWST",
    "Ironwood Pharmaceuticals": "IRWD",
    "Mineralys Therapeutics": "MLYS",
    "Legend Biotech": "LEGN",
    "Achieve Life Sciences": "ACHV",
    "Artiva Biotherapeutics": "ARTV",
    "Taysha Gene Therapies": "TSHA",
    "Nkarta Therapeutics": "NKTX",
    "Candel Therapeutics": "CADL",
    "AtaiBeckley": "ATAI",
    "Nektar Therapeutics": "NKTR",
    "GH Research": "GHRS",
    "Arcus Biosciences": "RCUS",
    "BioNTech": "BNTX",
    "Tango Therapeutics": "TNGX",
    "Inhibrx Biosciences": "INBX",
    "Canopy Growth": "CGC",
    "Replimune": "REPL",
    "West Pharmaceutical Services": "WST",
    "Vitrolife": "VITR.ST",
    "COMPASS Pathways": "CMPS",
    "Organon": "OGN",
    "Sagimet Biosciences": "SGMT",
    "Absci": "ABSI",
    "Kiniksa Pharmaceuticals": "KNSA",
    "WAVE Life Sciences": "WVE",
    "ICON": "ICLR",
    "DCC": "DCC.L",
    "Biogen": "BIIB",
    "Glaukos": "GKOS",
    "Toyota Tsusho": "8015.T",
    "CVS Health": "CVS",
    "Celcuity": "CELC",
    "Cullinan Therapeutics": "CGEM",
    "Ardelyx": "ARDX",
    "LG Chem": "051910.KS",
    "Yakult Honsha": "2267.T",
    "Teva Pharmaceutical Industries": "TEVA",
    "Edgewise Therapeutics": "EWTX",
    "Cytokinetics": "CYTK",
    "BillionToOne": "BLLN",
    "Avalo Therapeutics": "AVTX",
    "InflaRx": "IFRX",
    "MannKind": "MNKD",
    "Zealand Pharma": "ZEAL.CO",
    "Viatris": "VTRS",
    "BioGaia": "BIOG-B.ST",
    "Nanobiotix": "NANO.PA",
    "MBX Biosciences": "MBX",
    "UniQure": "QURE",
    "PTC Therapeutics": "PTCT",
    "Moderna": "MRNA",
    "NewAmsterdam Pharma": "NAMS",
    "Olympus": "7733.T",
    "Asahi Kasei": "3407.T",
    "PharmaNutra": "PHN.MI",
    "Vera Therapeutics": "VERA",
    "Nippon Suisan Kaisha": "1332.T",
    "Renascience": "RNSC",
    "Noveris Health Sciences": "NVRI",
    "Sellas Life Sciences Group": "SLS",
    "Hamamatsu Photonics": "6965.T",
    "Towa Pharmaceutical": "4553.T",
    "Suzuken Group": "9987.T",
    "Terumo": "4543.T",
    "Suven Life Sciences": "SUVEN.NS",
    "Sartorius": "SRT3.DE",
    "Immunovant": "IMVT",
    "UBE Corporation": "4208.T",
    "Roivant Sciences": "ROIV",
    "BioMarin Pharmaceutical": "BMRN",
    "Immunome": "IMNM",
    "Scholar Rock": "SRRK",
    "Biohaven": "BHVN",
    "Erasca": "ERAS",
    "Agilent Technologies": "A",
    "Bruker": "BRKR",
    "Indaptus Therapeutics": "INDP",
    "C4 Therapeutics": "CCCC",
    "Semnur Pharmaceuticals": "SMNR",
    "Curasight": "CURAS.CO",
    "Aclaris Therapeutics": "ACRS",
    "Health Catalyst": "HCAT",
    "Rezolute": "RZLT",
    "Abivax": "ABVX",
    "The Cooper Companies": "COO",
    "Nuvalent": "NUVL",
    "Alto Neuroscience": "ANRO",
    "Clover Health": "CLOV",
    "Nurix Therapeutics": "NRIX",
    "Alumis": "ALMS",
    "Enliven Therapeutics": "ELVN",
    "Rapport Therapeutics": "RAPP",
    "Intellia Therapeutics": "NTLA",
    "OmniAb": "OABI",
    "Solid Biosciences": "SLDB",
    "Elicio Therapeutics": "ELTX",
    "Evonik Industries": "EVK.DE",
    "PolyPeptide Group": "PPGN.SW",
    "Outlook Therapeutics": "OTLK",
    "Definium Therapeutics": "DFTX",
    "Apogee Therapeutics": "APGE",
    "Nuvectis Pharma": "NVCT",
    "Autolus Therapeutics": "AUTL",
    "Iovance Biotherapeutics": "IOVA",
    "NeoGenomics": "NEO",
    "Adaptive Biotechnologies": "ADPT",
    "Bio-Techne": "TECH",
    "Kymera Therapeutics": "KYMR",
    "CapForce": "CAPS",
    "Zura Bio": "ZURA",
    "GNI Group": "2160.T",
    "AbCellera Biologics": "ABCL",
    "Charles River Laboratories International": "CRL",
    "Contineum Therapeutics": "CNTP",
    "Ultragenyx Pharmaceutical": "RARE",
    "Zenas BioPharma": "ZBIO",
    "Codexis": "CDXS",
    "Damora Therapeutics": "DAMO",
    "GENFIT": "GNFT.PA",
    "Toyobo": "3101.T",
    "Bioventus": "BVS",
    "REGENXBIO": "RGNX",
    "Omeros": "OMER",
    "Crinetics Pharmaceuticals": "CRNX",
    "Agios Pharmaceuticals": "AGIO",
    "Viking Therapeutics": "VKTX",
    "Xenon Pharmaceuticals": "XENE",
    "BridgeBio Pharma": "BBIO",
    "Satellos Bioscience": "MSCL.TO",
    "Kuros Biosciences": "KURN.SW",
    "Aardvark Therapeutics": "AARD",
    "Sensei Biotherapeutics": "SNSE",
    "Wacker-Chemie": "WCH.DE",
    "Denali Therapeutics": "DNLI",
    "Annexon Biosciences": "ANNX",
    "Camurus": "CAMX.ST",
    "Abbott Laboratories": "ABT",
    "Orion": "ORNBV.HE",
    "Oruka Therapeutics": "ORKA",
    "Nuvation Bio": "NUVB",
    "Xencor": "XNCR",
    "Palvella Therapeutics": "PVLA",
    "Vor Biopharma": "VOR",
    "Nykode Therapeutics": "NYKD.OL",
    "Arrowhead Pharmaceuticals": "ARWR",
    "Thermo Fisher Scientific": "TMO",
    "Quest Diagnostics": "DGX",
    "Hansa Biopharma": "HNSA.ST",
    "Circio": "CRNA.ST",
    "Agenus": "AGEN",
    "ORIC Pharmaceuticals": "ORIC",
    "Shiseido": "4911.T",
    "Repligen": "RGEN",
    "Incyte": "INCY",
    "GE HealthCare": "GEHC",
    "Bausch Health Companies": "BHC",
    "Septerna": "SEPN",
    "UroGen Pharma": "URGN",
    "Travere Therapeutics": "TVTX",
    "ROHTO Pharmaceutical": "4527.T",
    "Halozyme Therapeutics": "HALO",
    "Belite Bio": "BLTE",
    "GeneDx (USA)": "GDYN",
    "Inovio Pharmaceuticals": "INO",
    "Capricor Therapeutics": "CAPR",
    "Amylyx Pharmaceuticals": "AMLX",
    "Haemonetics": "HAE",
    "Humacyte": "HUMA",
    "Oxford Nanopore Technologies": "ONT.L",
    "Bavarian Nordic": "BAVA.CO",
    "CSL": "CSL.AX",
    "Ascendis Pharma": "ASND",
    "Vir Biotechnology": "VIR",
    # Asia / international
    "Medigen Vaccines Biologics": "6547.TWO",
    "TiumBio": "321550.KQ",
    "OPTUS Pharmaceutical": "131030.KQ",
    "Helixmith": "084990.KQ",
    "Bukwang Pharmaceutical": "003000.KS",
    "CStone Pharmaceuticals": "2616.HK",
    "Sichuan Huiyu Pharmaceutical": "688553.SS",
    "Caliway Biopharmaceuticals": "6919.TW",
    "Unitika": "3103.T",
    "Medipost": "078160.KQ",
    "ToolGen": "199800.KQ",
    "HST Global": "HSTG",
    "CARsgen Therapeutics": "2171.HK",
    "Lin Bioscience": "6464.TWO",
    "Qurient Therapeutics": "115180.KQ",
    "STCube": "066790.KQ",
    "Frontier Biotechnologies": "688221.SS",
    "OliX Pharmaceuticals": "226950.KQ",
    "Denka Company": "4061.T",
    "Holy Stone Enterprise": "3026.TW",
    "Beijing Wantai Biological Pharmacy": "603392.SS",
    "Chengdu Olymvax Biopharmaceuticals": "688319.SS",
    "Oncolys BioPharma": "4588.T",
    "Sakai Chemical Industry": "4078.T",
    "Sun Pharma Advanced Research": "532872.BO",
    "HanAll BioPharma": "009420.KS",
    "D&D Pharmatech": "141080.KQ",
    "PharmaEssentia": "6446.TWO",
    "L&C BIO": "290650.KQ",
    "Ipca Laboratories": "IPCALAB.NS",
    "Bora Pharmaceuticals": "6472.TWO",
    "Shanghai Serum BioTechnology": "688336.SS",
    "Alterity Therapeutics": "ATH.AX",
    "PYC Therapeutics": "PYC.AX",
    "Neuren Pharmaceuticals": "NEU.AX",
    "Sichuan Biokin Pharmaceutical": "688506.SS",
    "Beijing Hotgen Biotech": "688068.SS",
    "Easton Biopharmaceuticals": "688276.SS",
    "Health and Happiness (H&H) International Holdings": "1112.HK",
    "Chongqing Lummy Pharmaceutical": "300006.SZ",
    "HLB Pharmaceutical": "047920.KQ",
    "Sam Chun Dang Pharm": "300720.KQ",
    "HLB LifeScience": "067630.KQ",
    "Genscript Biotech": "1548.HK",
    "Peptron": "087010.KQ",
    "Mezzion Pharma": "140410.KQ",
    "Fosun International": "0656.HK",
    "DNA Link": "144510.KQ",
    "Marksans Pharma": "MARKSANS.NS",
    "JenKem Technology": "300199.SZ",
    "Hanmi Pharmaceutical": "128940.KS",
    "Zhuzhou Qianjin Pharmaceutical": "600479.SS",
    "Helus Pharma": "HLS",
    "Caris Life Sciences": "CAI",
}
