"""Manual ticker mapping for pharma market movers companies."""

TICKER_MAP = {
    "10x Genomics": "TXG",
    "3-D Matrix": "7777.T",
    "3M": "MMM",
    "Aardvark Therapeutics": "AARD",
    "Abbott Laboratories": "ABT",
    "AbCellera Biologics": "ABCL",
    "Abivax": "ABVX",
    "ABL Bio": "298380.KQ",
    "Absci": "ABSI",
    "AC Immune": "ACIU",
    "Achieve Life Sciences": "ACHV",
    "Aclaris Therapeutics": "ACRS",
    "Adaptive Biotechnologies": "ADPT",
    "ADMA Biologics": "ADMA",
    "Agenus": "AGEN",
    "Agilent Technologies": "A",
    "Agios Pharmaceuticals": "AGIO",
    "Ajinomoto": "2802.T",
    "Aktis Oncology": "AKTS",
    "Alcon": "ALC",
    "Alkermes": "ALKS",
    "Allergy Therapeutics": "AGY.L",
    "Allogene Therapeutics": "ALLO",
    "Alnylam Pharmaceuticals": "ALNY",
    "Alpha Cognition": "ACOG",
    "Alpha Teknova": "TKNO",
    "Alphamab Oncology": "9966.HK",
    "Alteogen": "196170.KQ",
    "Alterity Therapeutics": "ATH.AX",
    "Alto Neuroscience": "ANRO",
    "Alumis": "ALMS",
    "Alvotech": "ALVO",
    "Amneal Pharmaceuticals": "AMRX",
    "Amphastar Pharmaceuticals": "AMPH",
    "Amylyx Pharmaceuticals": "AMLX",
    "AnaptysBio": "ANAB",
    "AngioDynamics": "ANGO",
    "Anika Therapeutics": "ANIK",
    "Annexon Biosciences": "ANNX",
    "Anteris Technologies": "AVR",
    "Apellis Pharmaceuticals": "APLS",
    "Apogee Therapeutics": "APGE",
    "Aquestive Therapeutics": "AQST",
    "Arcturus Therapeutics": "ARCT",
    "Arcus Biosciences": "RCUS",
    "Ardelyx": "ARDX",
    "argenx": "ARGX",
    "Armata Pharmaceuticals": "ARMP",
    "ArriVent Biopharma": "AVBP",
    "Arrowhead Pharmaceuticals": "ARWR",
    "ARS Pharmaceuticals": "ARS",
    "Artiva Biotherapeutics": "ARTV",
    "Asahi Kasei": "3407.T",
    "Ascendis Pharma": "ASND",
    "Ascletis Pharma": "1672.HK",
    "ASKA Pharmaceutical": "4514.T",
    "ASP Isotopes": "ASPI",
    "Assembly Biosciences": "ASMB",
    "Astellas Pharma": "4503.T",
    "AtaiBeckley": "ATAI",
    "Aura Biosciences": "AURA",
    "Aurinia Pharmaceuticals": "AUPH",
    "Autobio Diagnostics": "300832.SZ",
    "Autolus Therapeutics": "AUTL",
    "Avalo Therapeutics": "AVTX",
    "AxoGen": "AXGN",
    "Axsome Therapeutics": "AXSM",
    "Azenta": "AZTA",
    "Bachem": "BANB.SW",
    "Bausch Health Companies": "BHC",
    "Bavarian Nordic": "BAVA.CO",
    "Baxter International": "BAX",
    "Beam Therapeutics": "BEAM",
    "Beijing Hotgen Biotech": "688068.SS",
    "Beijing Wantai Biological Pharmacy": "603392.SS",
    "Belite Bio": "BLTE",
    "Bicara Therapeutics": "BCAX",
    "BillionToOne": "BLLN",
    "Bio-Techne": "TECH",
    "Bio-Thera Solutions": "688177.SS",
    "BioAge Labs": "BIOA",
    "BioArctic": "BIOA-B.ST",
    "BioCryst Pharmaceuticals": "BCRX",
    "BioDlink International Company": "688657.SS",
    "BioForce Nanosciences": "BFNH",
    "BioGaia": "BIOG-B.ST",
    "Biogen": "BIIB",
    "Biohaven": "BHVN",
    "Biolife Solutions": "BLFS",
    "BioMarin Pharmaceutical": "BMRN",
    "bioMérieux": "BIM.PA",
    "BioNTech": "BNTX",
    "Bioventus": "BVS",
    "Bora Pharmaceuticals": "6472.TWO",
    "Boston Scientific": "BSX",
    "Bridge Bio Pharma": "BBIO",
    "BridgeBio Pharma": "BBIO",
    "Bruker": "BRKR",
    "Bukwang Pharmaceutical": "003000.KS",
    "BWX Technologies": "BWXT",
    "C4 Therapeutics": "CCCC",
    "Caliway Biopharmaceuticals": "6919.TW",
    "Camurus": "CAMX.ST",
    "Candel Therapeutics": "CADL",
    "Canopy Growth": "CGC",
    "CapForce": "CAPS",
    "Capricor Therapeutics": "CAPR",
    "Caregen": "214370.KQ",
    "Caris Life Sciences": "CAI",
    "CARsgen Therapeutics": "2171.HK",
    "Catalyst Pharmaceuticals": "CPRX",
    "Celanese": "CE",
    "Celcuity": "CELC",
    "Celldex Therapeutics": "CLDX",
    "Cellectis": "CLLS",
    "Centessa Pharmaceuticals": "CNTA",
    "CG Oncology": "CGON",
    "Charles River Laboratories International": "CRL",
    "Chengdu Olymvax Biopharmaceuticals": "688319.SS",
    "Chongqing Lummy Pharmaceutical": "300006.SZ",
    "Chugai Pharmaceutical": "4519.T",
    "Circio": "CRNA.ST",
    "Clarity Pharmaceuticals": "CLX.AX",
    "Climb Bio": "CLYM",
    "Clover Biopharmaceuticals": "2197.HK",
    "Clover Health": "CLOV",
    "Codexis": "CDXS",
    "Cogent Biosciences": "COGT",
    "Collegium Pharmaceutical": "COLL",
    "COMPASS Pathways": "CMPS",
    "Compass Therapeutics": "CMPX",
    "CONBA group": "002332.SZ",
    "Contineum Therapeutics": "CNTP",
    "Corcept Therapeutics": "CORT",
    "CorMedix Therapeutics": "CRMD",
    "Corvus Pharmaceuticals": "CRVS",
    "Cosmo Pharmaceuticals": "COPN.SW",
    "Crescent Biopharma": "CBIO",
    "Crinetics Pharmaceuticals": "CRNX",
    "CSL": "CSL.AX",
    "CStone Pharmaceuticals": "2616.HK",
    "Cullinan Therapeutics": "CGEM",
    "Curasight": "CURAS.CO",
    "Curative Biotechnology": "CURV",
    "CVS Health": "CVS",
    "CytoDyn": "CYDY",
    "Cytokinetics": "CYTK",
    "D&D Pharmatech": "141080.KQ",
    "Damora Therapeutics": "DAMO",
    "Danaher": "DHR",
    "DBV Technologies": "DBVT",
    "DCC": "DCC.L",
    "Definium Therapeutics": "DFTX",
    "Denali Therapeutics": "DNLI",
    "Denka Company": "4061.T",
    "Dermapharm Holding": "DMP.DE",
    "Design Therapeutics": "DSGN",
    "Dianthus Therapeutics": "DNTH",
    "Disc Medicine": "IRON",
    "DNA Link": "144510.KQ",
    "Dr. Reddy's Laboratories": "DRREDDY.NS",
    "Dyne Therapeutics": "DYN",
    "Easton Biopharmaceuticals": "688276.SS",
    "Eckert & Ziegler Group": "EUZ.DE",
    "Eczacibasi Pharmaceuticals": "ECZYT.IS",
    "Edgewise Therapeutics": "EWTX",
    "Eisai": "4523.T",
    "Eledon Pharmaceuticals": "ELDN",
    "Elicio Therapeutics": "ELTX",
    "Emcure Pharmaceuticals": "EMCURE.NS",
    "enGene Therapeutics": "ENGN",
    "Enliven Therapeutics": "ELVN",
    "Erasca": "ERAS",
    "Eton Pharmaceuticals": "ETON",
    "Eurofins Scientific": "ERF.PA",
    "Evolus": "EOLS",
    "Evommune": "EVMN",
    "Evonik Industries": "EVK.DE",
    "Exelixis": "EXEL",
    "EyePoint Pharmaceuticals": "EYPT",
    "Faes Farma": "FAE.MC",
    "Faeth Therapeutics": "FAETH",
    "Fennec Pharmaceuticals": "FENC",
    "Forte Biosciences": "FBRX",
    "Fosun International": "0656.HK",
    "Frontier Biotechnologies": "688221.SS",
    "FUJIFILM Holdings": "4901.T",
    "Fujitsu": "6702.T",
    "Galderma": "GALD.SW",
    "Galectin Therapeutics": "GALT",
    "Galecto": "GLTO",
    "Gan & Lee Pharmaceuticals": "603087.SS",
    "GE HealthCare": "GEHC",
    "GeneDx (USA)": "GDYN",
    "GENFIT": "GNFT.PA",
    "Genomma Lab Internacional": "LABB.MX",
    "Genscript Biotech": "1548.HK",
    "GH Research": "GHRS",
    "Gingko Bioworks Holding": "DNA",
    "Ginkgo Bioworks Holdings": "DNA",
    "Glaukos": "GKOS",
    "Globus Medical": "GMED",
    "GNI Group": "2160.T",
    "Green Thumb Industries": "GTBIF",
    "Grifols": "GRF.MC",
    "Haemonetics": "HAE",
    "Halozyme Therapeutics": "HALO",
    "Hamamatsu Photonics": "6965.T",
    "HanAll BioPharma": "009420.KS",
    "Hanmi Pharmaceutical": "128940.KS",
    "Hansa Biopharma": "HNSA.ST",
    "Harbour BioMed": "02142.HK",
    "Harmony Biosciences": "HRMY",
    "Harrow": "HROW",
    "Health and Happiness (H&H) International Holdings": "1112.HK",
    "Health Catalyst": "HCAT",
    "Heilongjiang ZBD Pharmaceutical": "600664.SS",
    "Helixmith": "084990.KQ",
    "Helus Pharma": "HLS",
    "Hikma Pharmaceuticals": "HIK.L",
    "HLB": "028300.KQ",
    "HLB LifeScience": "067630.KQ",
    "HLB Pharmaceutical": "047920.KQ",
    "Holy Stone Enterprise": "3026.TW",
    "HST Global": "HSTG",
    "Hugel": "145020.KQ",
    "Humacyte": "HUMA",
    "ICON": "ICLR",
    "Idorsia": "IDIA.SW",
    "Illumina": "ILMN",
    "Immuneering Corporation": "IMRX",
    "ImmunityBio": "IBRX",
    "Immunocore": "IMCR",
    "Immunome": "IMNM",
    "Immunovant": "IMVT",
    "Incyte": "INCY",
    "Indaptus Therapeutics": "INDP",
    "InflaRx": "IFRX",
    "Inhibrx Biosciences": "INBX",
    "Innovent Biologics": "1801.HK",
    "Inovio Pharmaceuticals": "INO",
    "Insmed": "INSM",
    "Integra LifeSciences": "IART",
    "Intellia Therapeutics": "NTLA",
    "International Flavors & Fragrances": "IFF",
    "InventisBio": "688197.SS",
    "Inventiva": "IVA.PA",
    "Invivyd": "IVVD",
    "Ionis Pharmaceuticals": "IONS",
    "Iovance Biotherapeutics": "IOVA",
    "Ipca Laboratories": "IPCALAB.NS",
    "Ipsen": "IPN.PA",
    "Ironwood Pharmaceuticals": "IRWD",
    "Ishihara Sangyo Kaisha": "4028.T",
    "iX Biopharma": "IXB.AX",
    "Jade Biosciences": "JBIO",
    "Japan Tobacco": "2914.T",
    "JenKem Technology": "300199.SZ",
    "Jiangsu Aidea Pharmaceutical": "300434.SZ",
    "Jubilant Ingrevia": "JUBLINGREA.NS",
    "Jumpcan Pharmaceutical Group": "603676.SS",
    "KalVista Pharmaceuticals": "KALV",
    "Kerry Group": "KRZ.IR",
    "Keymed Biosciences": "9926.HK",
    "Kiniksa Pharmaceuticals": "KNSA",
    "Kodiak Sciences": "KOD",
    "Krka Group": "KRKG.LJ",
    "Krystal Biotech": "KRYS",
    "Kuros Biosciences": "KURN.SW",
    "Kymera Therapeutics": "KYMR",
    "Kyowa Kirin": "4151.T",
    "Kyverna Therapeutics": "KYTX",
    "L&C BIO": "290650.KQ",
    "LB Pharmaceuticals": "LBRX",
    "Legend Biotech": "LEGN",
    "Leidos": "LDOS",
    "Lepu Biopharma": "2157.HK",
    "Lexicon Pharmaceuticals": "LXRX",
    "LG Chem": "051910.KS",
    "LigaChem Biosciences": "141080.KQ",
    "Ligand Pharmaceuticals": "LGND",
    "Lin Bioscience": "6464.TWO",
    "Lion": "3591.T",
    "Liquidia Corporation": "LQDA",
    "Lonza": "LONN.SW",
    "Luye Pharma Group": "2186.HK",
    "Mabwell (Shanghai) Bioscience": "688062.SS",
    "MacroGenics": "MGNX",
    "Madrigal Pharmaceuticals": "MDGL",
    "MannKind": "MNKD",
    "MapLight Therapeutics": "MPLT",
    "Maravai LifeSciences": "MRVI",
    "Marksans Pharma": "MARKSANS.NS",
    "MBX Biosciences": "MBX",
    "McKesson": "MCK",
    "Medigen Vaccines Biologics": "6547.TWO",
    "Medipal Holdings": "7459.T",
    "Medipost": "078160.KQ",
    "Medtronic": "MDT",
    "MeiraGTx": "MGTX",
    "Merck KGaA": "MRK.DE",
    "Mesoblast": "MESO",
    "Mezzion Pharma": "140410.KQ",
    "Milestone Pharmaceuticals": "MIST",
    "Mineralys Therapeutics": "MLYS",
    "Mitsubishi Chemical": "4188.T",
    "Mitsui & Co": "8031.T",
    "Mitsui Chemicals": "4183.T",
    "Moderna": "MRNA",
    "Monopar Therapeutics": "MNPR",
    "Monte Rosa Therapeutics": "GLUE",
    "MoonLake Immunotherapeutics": "MLTX",
    "Nagase & Co": "4021.T",
    "Nanexa": "NANEXA.ST",
    "Nanobiotix": "NANO.PA",
    "Natera": "NTRA",
    "Nature Cell": "007390.KQ",
    "Nautilus Biotechnology": "NAUT",
    "Nektar Therapeutics": "NKTR",
    "NeoGenomics": "NEO",
    "Nestlé": "NESN.SW",
    "Neumora Therapeutics": "NMRA",
    "Neuren Pharmaceuticals": "NEU.AX",
    "Neurocrine Biosciences": "NBIX",
    "Neurogene": "NRGN",
    "NewAmsterdam Pharma": "NAMS",
    "Newron Pharmaceuticals": "NWRN.SW",
    "Nihon Nohyaku": "4997.T",
    "Nippon Kayaku": "4272.T",
    "Nippon Shinyaku": "4516.T",
    "Nippon Suisan Kaisha": "1332.T",
    "Nissan Chemical": "4021.T",
    "Nitto Denko": "6988.T",
    "Nkarta Therapeutics": "NKTX",
    "Novavax": "NVAX",
    "Noveris Health Sciences": "NVRI",
    "Novonesis": "NSIS-B.CO",
    "Nurix Therapeutics": "NRIX",
    "Nuvalent": "NUVL",
    "Nuvation Bio": "NUVB",
    "Nuvectis Pharma": "NVCT",
    "Nykode Therapeutics": "NYKD.OL",
    "Ocular Therapeutix": "OCUL",
    "Oculis": "OCS",
    "OliX Pharmaceuticals": "226950.KQ",
    "Olympus": "7733.T",
    "Omeros": "OMER",
    "OmniAb": "OABI",
    "Oncolys BioPharma": "4588.T",
    "Ono Pharmaceutical": "4507.T",
    "OPTUS Pharmaceutical": "131030.KQ",
    "Opus Genetics": "IRD",
    "Orchid Pharma": "ORCHPHARMA.NS",
    "Organon": "OGN",
    "ORIC Pharmaceuticals": "ORIC",
    "Orion": "ORNBV.HE",
    "Oruka Therapeutics": "ORKA",
    "Oscotec": "039200.KQ",
    "OSE Immunotherapeutics": "OSE.PA",
    "Otsuka Holdings": "4578.T",
    "Outlook Therapeutics": "OTLK",
    "Ovid Therapeutics": "OVID",
    "Oxford BioMedica": "OXB.L",
    "Oxford Nanopore Technologies": "ONT.L",
    "Palvella Therapeutics": "PVLA",
    "PeptiDream": "4587.T",
    "Peptron": "087010.KQ",
    "Perrigo": "PRGO",
    "Personalis": "PSNL",
    "PharmaEssentia": "6446.TWO",
    "PharmaNutra": "PHN.MI",
    "Pharvaris": "PHVS",
    "Phathom Pharmaceuticals": "PHAT",
    "Plus Therapeutics": "PSTV",
    "PolyPeptide Group": "PPGN.SW",
    "Praxis Precision Medicines": "PRAX",
    "Precigen": "PGEN",
    "Prelude Therapeutics": "PRLD",
    "Prestige Consumer Healthcare": "PBH",
    "Prime Medicine": "PRME",
    "Procter & Gamble": "PG",
    "ProMIS Neurosciences": "PMN.TO",
    "ProQR Therapeutics": "PRQR",
    "Protagonist Therapeutics": "PTGX",
    "PTC Therapeutics": "PTCT",
    "PYC Therapeutics": "PYC.AX",
    "Pyc Therapeutics": "PYC.AX",
    "Qiagen": "QGEN",
    "Quest Diagnostics": "DGX",
    "Qurient Therapeutics": "115180.KQ",
    "Rapport Therapeutics": "RAPP",
    "Reckitt Benckiser": "RKT.L",
    "Recordati": "REC.MI",
    "Recursion Pharmaceuticals": "RXRX",
    "Regencell Bioscience": "RGC",
    "REGENXBIO": "RGNX",
    "Relay Therapeutics": "RLAY",
    "RemeGen": "688331.SS",
    "Renascience": "RNSC",
    "Repligen": "RGEN",
    "Replimune": "REPL",
    "Revolution Medicines": "RVMD",
    "Rezolute": "RZLT",
    "Roche": "ROG.SW",
    "Rocket Pharmaceuticals": "RCKT",
    "ROHTO Pharmaceutical": "4527.T",
    "Rohto Pharmaceutical": "4527.T",
    "Roivant Sciences": "ROIV",
    "SAB BIO": "SABS",
    "Sagimet Biosciences": "SGMT",
    "Sakai Chemical Industry": "4078.T",
    "Sam Chun Dang Pharm": "300720.KQ",
    "Samsung Biologics": "207940.KS",
    "Sanara MedTech": "SMTI",
    "SanBio": "4592.T",
    "Sandoz Group": "SDZ.SW",
    "Santen Pharmaceutical": "4536.T",
    "Santhera Pharmaceuticals": "SREN.SW",
    "Sarepta Therapeutics": "SRPT",
    "Sartorius": "SRT3.DE",
    "Satellos Bioscience": "MSCL.TO",
    "SBI Holdings": "8473.T",
    "Scancell": "SCLP.L",
    "Scholar Rock": "SRRK",
    "Sellas Life Sciences Group": "SLS",
    "Semnur Pharmaceuticals": "SMNR",
    "Sensei Biotherapeutics": "SNSE",
    "Septerna": "SEPN",
    "Shanghai Henlius Biotech": "2696.HK",
    "Shanghai Serum BioTechnology": "688336.SS",
    "Shanghai Shenqi Pharmaceutical Investment Management": "600613.SS",
    "Shattuck Labs": "STTK",
    "Shilpa Medicare": "SHILPAMED.NS",
    "Shimadzu": "7701.T",
    "Shionogi": "4507.T",
    "Shiseido": "4911.T",
    "Sichuan Biokin Pharmaceutical": "688506.SS",
    "Sichuan Huiyu Pharmaceutical": "688553.SS",
    "Sichuan Kelun-Biotech Biopharmaceutical": "688443.SS",
    "Siegfried": "SFZN.SW",
    "Silence Therapeutics": "SLN",
    "Simcere Pharmaceutical Group": "2096.HK",
    "Sino Biopharmaceutical": "1177.HK",
    "Sionna Therapeutics": "SION",
    "SK Chemicals": "285130.KQ",
    "Soleno Therapeutics": "SLNO",
    "Solid Biosciences": "SLDB",
    "Solventum": "SOLV",
    "Spyre Therapeutics": "SYRE",
    "STAAR Surgical": "STAA",
    "STCube": "066790.KQ",
    "Stoke Therapeutics": "STOK",
    "Strides Pharma Science": "STAR.NS",
    "Structure Therapeutics": "GPCR",
    "Stryker": "SYK",
    "SUGI Holdings": "7649.T",
    "Sumitomo Heavy Industries": "6302.T",
    "Sumitomo Pharma": "4506.T",
    "Summit Therapeutics": "SMMT",
    "Sun Pharma Advanced Research": "532872.BO",
    "Sundial Growers": "SNDL",
    "Sunshine Guojian Pharmaceutical (Shanghai)": "688336.SS",
    "Supernus Pharmaceuticals": "SUPN",
    "Supriya Lifescience": "SUPRIYA.NS",
    "Sutro Biopharma": "STRO",
    "Suven Life Sciences": "SUVEN.NS",
    "Suzuken Group": "9987.T",
    "Swedish Orphan Biovitrum": "SOBI.ST",
    "Syndax Pharmaceuticals": "SNDX",
    "Tango Therapeutics": "TNGX",
    "Tasly Pharma": "600535.SS",
    "Taysha Gene Therapies": "TSHA",
    "Teijin": "3401.T",
    "Teleflex": "TFX",
    "Terumo": "4543.T",
    "Teva Pharmaceutical Industries": "TEVA",
    "TG Therapeutics": "TGTX",
    "Tg Therapeutics": "TGTX",
    "The Cooper Companies": "COO",
    "Thermo Fisher Scientific": "TMO",
    "Tianquan Pharmaceutical": "300702.SZ",
    "Tilray": "TLRY",
    "TiumBio": "321550.KQ",
    "Tokuyama": "4043.T",
    "ToolGen": "199800.KQ",
    "Towa Pharmaceutical": "4553.T",
    "Toyobo": "3101.T",
    "Toyota Tsusho": "8015.T",
    "Transcenta Holding": "6628.HK",
    "Transgene": "TNG.PA",
    "Travere Therapeutics": "TVTX",
    "Treace Medical Concepts": "TMCI",
    "Trevi Therapeutics": "TRVI",
    "TuHURA Biosciences": "HURA",
    "Twist Bioscience": "TWST",
    "UBE Corporation": "4208.T",
    "Ultragenyx Pharmaceutical": "RARE",
    "UniQure": "QURE",
    "uniQure": "QURE",
    "United Therapeutics": "UTHR",
    "Unitika": "3103.T",
    "UroGen Pharma": "URGN",
    "Valneva": "VLA.PA",
    "Vaxcyte": "PCVX",
    "Vera Therapeutics": "VERA",
    "Verastem": "VSTM",
    "Vericel": "VCEL",
    "Viatris": "VTRS",
    "Vicore Pharma": "VICO.ST",
    "Viking Therapeutics": "VKTX",
    "Vir Biotechnology": "VIR",
    "Viridian Therapeutics": "VRDN",
    "Vitrolife": "VITR.ST",
    "Vor Biopharma": "VOR",
    "Wacker-Chemie": "WCH.DE",
    "WAVE Life Sciences": "WVE",
    "West Pharmaceutical Services": "WST",
    "WuXi AppTec": "2359.HK",
    "Xencor": "XNCR",
    "Xenon Pharmaceuticals": "XENE",
    "XOMA Royalty": "XOMA",
    "Xspray Pharma": "XSPRAY.ST",
    "Yakult Honsha": "2267.T",
    "YD Bio": "YD",
    "Youcare Pharmaceutical Group": "300015.SZ",
    "Zealand Pharma": "ZEAL.CO",
    "Zenas BioPharma": "ZBIO",
    "Zenith Energy": "ZEN",
    "Zentalis Pharmaceuticals": "ZNTL",
    "Zhangzhou Pien Tze Huang Pharmaceutical": "600436.SS",
    "Zhuzhou Qianjin Pharmaceutical": "600479.SS",
    "Zimmer Biomet": "ZBH",
    "Zura Bio": "ZURA",
    "Zymeworks": "ZYME",
    "Innate Pharma": "IPA.PA",
    "LEXEO Therapeutics": "LEXO",
    "NIOX": "NIOX.L",
    "Nestlé": "NESN.SW",
    "Nestl\u00e9": "NESN.SW",
    "Nxera Pharma": "NXR",
    "Philogen": "PHIL.MI",
    "Sana Biotechnology": "SANA",
    "Telix Pharmaceuticals": "TLX.AX",
    "Zai Lab": "ZLAB",
    "bioMérieux": "BIM.PA",
    "bioM\u00e9rieux": "BIM.PA",
}
